version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: exercise_tracker_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: exercise_tracker
    restart: unless-stopped

volumes:
  mongodb_data:
    name: exercise_tracker_mongodb_data